---
# Source: cert-manager/charts/cert-manager/charts/cainjector/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-cainjector
  namespace: "default"
  labels:
    app: cainjector
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/instance:  RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cainjector-v0.11.0
