apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:default:mbirchwebsite"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  name: mbirchwebsite
  namespace: mbirchdk
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: mbirchwebsite
spec:
  ports:
  - name: http-mbirchwebsite
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https-mbirchwebsite
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-mbirchwebsite
  sessionAffinity: None
  type: ClusterIP
