argo-cd:
  installCRDs: false
  configs:
    secret:
      createSecret: true

  repoServer:
    env:
    - name: "ARGOCD_GIT_MODULES_ENABLED"
      value: "false"
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: true
          prometheus.io/path: /metrics
          prometheus.io/port: 8084
  controller:
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: true
          prometheus.io/path: /metrics
          prometheus.io/port: 8082
  server:
    certificate:
      domain: argo.birchen.tech
      enabled: false
    extraArgs:
      - --insecure
    config:
      users.anonymous.enabled: "false"
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: true
          prometheus.io/path: /metrics
          prometheus.io/port: 8083
    ingress:
      enabled: true
      https: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - argo.birchen.tech
      tls:
        - secretName: argo.birchen.tech
          hosts:
           - argo.birchen.tech
certificate:
  enabled: true
  name: argo.birchen.tech
  dnsNames:
    - argo.birchen.tech
  issuer:
    kind: ClusterIssuer
    name: letsencrypt-prod