apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harmikkelhatpaa
  namespace: funprojects
spec:
  rules:
  - host: harmikkelhatpaa.birchen.tech
    http:
      paths:
      - backend:
          service:
            name: harmikkelhatpaa-svc
            port:
              number: 80
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - harmikkelhatpaa.birchen.tech
    secretName: harmikkelhatpaa.birchen.tech

  certificate:
    harmikkelhatpaa.birchen.tech:
      namespace: funprojects
      spec:
        secretName: harmikkelhatpaa.birchen.tech
        issuerRef:
          name: letsencrypt-prod
          kind: ClusterIssuer
          group: cert-manager.io
        dnsNames:
          - harmikkelhatpaa.birchen.tech
