argoApps:
  server: https://kubernetes.default.svc
  repoUrl: https://github.com/mbirchdk/home-k8s.git
  namespace: default
  project: mikkel
  namespaceArgo: argocd
  
  applications:
    
    longhorn:
      path: deployments/longhorn
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: longhorn-system

    cluster-bootstrapping:
      path: deployments/cluster-bootstrapping
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: default

    linkerd:
      path: deployments/linkerd
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: linkerd
      
    linkerd-viz:
      path: deployments/linkerd-viz
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: linkerd

    sealedsecret:
      path: deployments/sealedSecret-arm
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: sealedsecret
    
    ddns:
      path: deployments/ddns
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: ddns

    mbirchdk:
      path: deployments/mbirchdk
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: mbirchdk

    cert-manager:
      path: deployments/cert-manager-arm
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: cert-manager

    homeassistant:
      path: deployments/homeassistant
      targetRevision: main
      valueFiles:
        - sensors-values.yaml
        - configuration-values.yaml
        - secrets-values.yaml
      namespace: homeassistant

    zigbee2mqtt:
      path: deployments/zigbee2mqtt
      targetRevision: main
      valueFiles:
        - values-all.yaml
      namespace: homeassistant

    livescorerapi:
      path: deployments/livescorerapi
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: homeassistant

  projects:
    mikkel:
      description: apps belonging to mikkel
      sources:
        - https://github.com/mbirchdk/home-k8s.git
      destinations:
        - namespace: mbirchdk
          server: https://kubernetes.default.svc
        - namespace: cert-manager
          server: https://kubernetes.default.svc
        - namespace: funprojects
          server: https://kubernetes.default.svc
        - namespace: homeassistant
          server: https://kubernetes.default.svc
        - namespace: sealedsecret
          server: https://kubernetes.default.svc
        - namespace: longhorn-system
          server: https://kubernetes.default.svc
        - namespace: pihole
          server: https://kubernetes.default.svc
        - namespace: vpn
          server: https://kubernetes.default.svc
        - namespace: ddns
          server: https://kubernetes.default.svc
          


