argoApps:
  server: https://kubernetes.default.svc
  repoUrl: https://github.com/mbirchdk/home-k8s.git
  namespace: default
  project: mikkel
  namespaceArgo: argocd
  
  applications:
    mbirchdk:
      path: deployments/mbirchdk
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: mbirchdk

    cert-manager:
      path: deployments/cert-manager-arm
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: cert-manager

    harmikkelhatpaa:
      project: funprojects
      path: deployments/harmikkelhatpaa
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: funprojects
    
    homeassistant:
      path: deployments/homeassistant
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: homeassistant

    sealedsecret:
      path: deployments/sealedSecret-arm
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: sealedsecret

  projects:
    mikkel:
      description: apps belonging to mikkel
      sources:
        - https://github.com/mbirchdk/home-k8s.git
      destinations:
        - namespace: mbirchdk
          server: https://kubernetes.default.svc
        - namespace: cert-manager
          server: https://kubernetes.default.svc
        - namespace: funprojects
          server: https://kubernetes.default.svc
        - namespace: homeassistant
          server: https://kubernetes.default.svc
        - namespace: sealedsecret
          server: https://kubernetes.default.svc


