argoApps:
  server: https://kubernetes.default.svc
  repoUrl: https://github.com/mbirchdk/home-k8s.git
  namespace: default
  project: default
  namespaceArgo: default
  
  
  applications:
    mbirchdk:
      path: deployments/mbirchdk
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: mbirchdk

  projects:
    mbirchdk:
      description: mbirch.dk hjemmeside
      sources:
        - https://github.com/mbirchdk/home-k8s.git
      destinations:
        - namespace: mbirchdk
          server: https://kubernetes.default.svc
