argoApps:
  server: https://kubernetes.default.svc
  repoUrl: https://github.com/mbirchdk/home-k8s.git
  namespace: default
  project: default
  namespaceArgo: argocd
  
  
  applications:
    mbirchdk:
      path: deployments/mbirchdk
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: mbirchdk
      
    cert-manager:
      path: deployments/cert-manager-arm
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: cert-manager

  projects:
    mbirchdk:
      description: mbirch.dk hjemmeside
      sources:
        - https://github.com/mbirchdk/home-k8s.git
      destinations:
        - namespace: mbirchdk
          server: https://kubernetes.default.svc

    cert-manager:
      description: cert manager
      sources:
        - https://github.com/mbirchdk/home-k8s.git
      destinations:
        - namespace: cert-manager
          server: https://kubernetes.default.svc
