argoApps:
  server: https://kubernetes.default.svc
  repoUrl: https://github.com/mbirchdk/home-k8s.git
  namespace: default
  project: default
  namespaceArgo: argocd
  
  
  applications:
    mbirchdk:
      path: deployments/mbirchdk
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: mbirchdk

    cert-manager:
      path: deployments/cert-manager-arm
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: cert-manager

    harmikkelhatpaa:
      project: funprojects
      path: deployments/harmikkelhatpaa
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: funprojects
    
    homeassistant:
      path: deployments/homeassistant
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: homeassistant

    sealedsecret:
      path: deployments/sealedSecret-arm
      targetRevision: main
      valueFiles:
        - values.yaml
      namespace: sealedsecret

  projects:
    mbirchdk:
      description: mbirch.dk hjemmeside
      sources:
        - https://github.com/mbirchdk/home-k8s.git
      destinations:
        - namespace: mbirchdk
          server: https://kubernetes.default.svc

    cert-manager:
      description: cert manager
      sources:
        - https://github.com/mbirchdk/home-k8s.git
      destinations:
        - namespace: cert-manager
          server: https://kubernetes.default.svc
        - namespace: kube-system
          server: https://kubernetes.default.svc
    
    funprojects:
      description: projects for fun
      sources:
        - https://github.com/mbirchdk/home-k8s.git
      destinations:
        - namespace: funprojects
          server: https://kubernetes.default.svc
    
    homeassistant:
      description: smart control for home
      sources:
        - https://github.com/mbirchdk/home-k8s.git
      destinations:
        - namespace: homeassistant
          server: https://kubernetes.default.svc
    
    sealedsecret:
      description: safe storage of secrets
      sources:
        - https://github.com/mbirchdk/home-k8s.git
      destinations:
        - namespace: sealedsecret
          server: https://kubernetes.default.svc
