apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
  namespace: homeassistant
data: 
  configuration.yaml: |
      {{- with .Values.configuration }}
        {{- toYaml . | nindent 6 }}
      {{- end }}

      # Configure a default setup of Home Assistant (frontend, api, etc)
      sensor: !include_dir_merge_list sensors/
      secret: !include_dir_merge_list secrets/
      group: !include groups.yaml
      automation: !include automations.yaml
      script: !include scripts.yaml
      scene: !include scenes.yaml

      frontend:    
        themes: !include_dir_merge_named themes

      
