apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  namespace: homeapps
spec:
  rules:
  - host: home.birchen.tech
    http:
      paths:
      - backend:
          service:
            name: home-assistant-svc
            port:
              name: http
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - home.birchen.tech
    secretName: home.birchen.tech
    
