configuration : 
  homeassistant:
    external_url: "https://home.birchen.tech:443"

  # Text to speech
  tts:
  - platform: google_translate

  # Alarm
  alarm_control_panel:
  - platform: manual
    name: House Alarm
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
  # LG TV
  webostv:
  - host: 192.168.86.174
    customize:
      sources:
      - youtube
      - netflix
      - disneyplus
  default_config:

  mobile_app:
  
  http:
    use_x_forwarded_for: true
    trusted_proxies: 
      - "10.0.0.0/8"
      - "192.168.86.72"
    ip_ban_enabled: true
    login_attempts_threshold: 5

  spotify:
    client_id: !secret spotify.client_id
    client_secret: !secret spotify.client_secret

  google_assistant:
    project_id: !secret google_assistant.project_id

  nest:
    client_id: !secret nest.client_id
    client_secret: !secret nest.client_secret
    project_id: !secret nest.project_id
    subscriber_id: !secret nest.subscriber_id

