{{- if (.Values.certificate) -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.namespace }}
spec:
  dnsNames:
  {{- range .Values.certificate.dnsNames }}
  - {{ .  }}
  {{- end }}
  issuerRef:
    group: cert-manager.io
    kind: {{ .Values.certificate.issuer.kind }}
    name: {{ .Values.certificate.issuer.name }}
  secretName: {{ .Values.certificate.name }}
{{- end -}}