argo-cd:
  installCRDs: false
  configs:
    secret:
      createSecret: true

  repoServer:
    env:
    - name: "ARGOCD_GIT_MODULES_ENABLED"
      value: "false"
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: true
          prometheus.io/path: /metrics
          prometheus.io/port: 8084
  controller:
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: true
          prometheus.io/path: /metrics
          prometheus.io/port: 8082
        extraArgs:
          - --repo-server-plaintext
  server:
    certificate:
      domain: argo.birchen.tech
      enabled: false
    extraArgs:
      - --insecure
    config:
      users.anonymous.enabled: "false"
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: true
          prometheus.io/path: /metrics
          prometheus.io/port: 8083
    ingress:
      enabled: true
      https: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod" 
        kubernetes.io/ingress.class: nginx
      hosts:
        - argo.birchen.tech
      tls:
        - secretName: argo.birchen.tech
          hosts:
           - argo.birchen.tech