apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: pihole
  name: pihole
  namespace: pihole
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pihole
    spec:
      volumes:
      - name: piehole-etc-volume
        persistentVolumeClaim:
          claimName: pihole-etc
      - name: piehole-dnsmasq-volume
        persistentVolumeClaim:
          claimName: pihole-dnsmasq
      containers:
      - image: pihole/pihole:2022.04.2
        imagePullPolicy: IfNotPresent
        name: pihole
        env:
        - name: TZ
          value: "Europe/Copenhagen"
        - name: DNS1
          value: "9.9.9.9"
        - name: DNS2
          value: "149.112.112.112"
        - name: ServerIP
          value: 192.168.86.72
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: password
        volumeMounts:
        - name: piehole-etc-volume
          mountPath: /etc/pihole/
        - name: piehole-dnsmasq-volume
          mountPath: /etc/dnsmasq.d/
        ports:
        - containerPort: 53
          hostPort: 53
          protocol: TCP
        - containerPort: 53
          hostPort: 53
          protocol: UDP
        - containerPort: 443
          hostPort: 4433
          name: https
          protocol: TCP
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
