apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: pihole
  namespace: pihole
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.10.0.0/20,10.0.0.0/20,192.168.86.0/24,85.184.157.184
spec:
  rules:
  - host: pihole.birchen.tech
    http:
      paths:
      - backend:
          service:
            name: pihole-svc
            port:
              name: http
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - pihole.birchen.tech
    secretName: pihole.birchen.tech
  