certificate:
  linkerd-trust-anchor:
    namespace: linkerd
    spec:
      secretName: linkerd-trust-anchor-temp
      duration: 87600h0m0s # ~10 years
      renewBefore: 24h0m0s
      commonName: linkerd-trust-anchor-temp
      issuerRef:
        name: ca-issuer
        kind: ClusterIssuer
        group: cert-manager.io