certificate:
  linkerd-identity-issuer:
    namespace: linkerd
    spec:
      secretName: linkerd-identity-issuer
      duration: 87600h0m0s # ~10 years
      renewBefore: 24h0m0s
      commonName: linkerd-identity-issuer
      issuerRef:
        name: ca-issuer
        kind: ClusterIssuer
        group: cert-manager.io

linkerd2:
  identity:
    issuer:
      tls:
        crtPEM: |
          refsecret
        keyPEM: |
          refsecret
  identityTrustAnchorsPEM: |
    refsecret
