{{- if .Values.issuers.selfsigned.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: infrastructure
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-issuer
  namespace: infrastructure
spec:
  secretName: ca-issuer
  duration: {{ .Values.issuers.selfsigned.duration }}
  renewBefore: {{ .Values.issuers.selfsigned.renewBefore }}
  commonName: {{ .Values.issuers.selfsigned.commonname }}
  isCA: true
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: infrastructure
spec:
  ca:
    secretName: ca-issuer
{{- end }}
