sealed-secrets:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod" 
    hostname: sealed-secrets.mbirch.dk
    path: /v1/cert.pem
    tls:
      - hosts:
          - sealed-secrets.mbirch.dk
        secretName: sealed-secrets.mbirch.dk