longhorn:  
  defaultSettings:
    defaultReplicaCount: 2  
  ingress:
    enabled: true
    host: longhorn.home.birchen.tech
    tls: true
    tlsSecret: longhorn.home.birchen.tech
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/24,85.184.157.184
certificate:
  enabled: true
  name: longhorn.home.birchen.tech
  dnsNames:
    - longhorn.home.birchen.tech
  issuer:
    kind: ClusterIssuer
    name: letsencrypt-prod

  