apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: livescorerapi
    app.kubernetes.io/version: 2021.6.3
  name: livescorerapi
  namespace: funprojects
spec:
  ports:
  - name: http-livescorerapi
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https-livescorerapi
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/name: livescorerapi
  sessionAffinity: None
  type: ClusterIP
